import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { 
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube
 } from 'react-icons/ai';
 import Image from 'next/image';
 import Avatar from '../public/externals/dev-ed-wave.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>SOBHAN Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        {/* First Page */}
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>SobhanNiroula</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a 
                  className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' 
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 
              className='text-5xl py-2 font-medium text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-teal-500'
            >
              Sobhan Niroula
            </h2>
            <h3 
              className='text-2xl py-2'
            >
              Software Developer
            </h3>
            <p 
              className='text-md py-5 leading-8 text-gray-800'
            >
              Software Developer. Tech Inthusiast. Fast Learner. Person With Never-Give-Up Attitude.
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-500'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>

          <div 
            className='mx-auto relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'
          >
            <Image src={Avatar} layout="fill" objectFit='cover' />
          </div>
        </section>

        {/* Second page*/}
        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p>
              {}
            </p>
          </div>
        </section>

      </main>

    </div>
  );
};
